//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_THP_2210900054_Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAO_CAO
    {
        public int ma_bao_cao { get; set; }
        public string noi_dung { get; set; }
        public int ma_video { get; set; }
        public System.DateTime ngay_bao_cao { get; set; }
        public string ma_quan_tri { get; set; }
    
        public virtual QUAN_TRI QUAN_TRI { get; set; }
        public virtual VIDEO VIDEO { get; set; }
    }
}
