//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_THP_2210900054_Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIDEO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VIDEO()
        {
            this.BAO_CAO = new HashSet<BAO_CAO>();
        }
    
        public int ma_video { get; set; }
        public string tieu_de { get; set; }
        public string mo_ta { get; set; }
        public string duong_dan { get; set; }
        public string hinh_anh { get; set; }
        public string the_loai { get; set; }
        public System.DateTime ngay_tao { get; set; }
        public string ma_quan_tri { get; set; }
        public Nullable<byte> trang_thai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAO_CAO> BAO_CAO { get; set; }
        public virtual QUAN_TRI QUAN_TRI { get; set; }
        public virtual DANH_MUC_VIDEO DANH_MUC_VIDEO { get; set; }
    }
}
